name: Node.js Test and Merge CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing node modules
        run: npm install

      - name: Testing the node modules
        run: npm test

  Compress_and_apply_to_AWS:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Compressing the project to the zip file
        run: zip -r webapp.zip .

      - name: Verifying whether we have zipped it
        run: ls -l

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run packer init
        id: init
        run: "packer init ./poc.pkr.hcl"

      - name: Run packer validate
        id: validate
        run: "packer validate ./poc.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: "packer build ./poc.pkr.hcl"